export {default as Home} from './Home';
export {default as Contact} from './Contact';
export {default as Cart} from './Cart';
export {default as Deals} from './Deals';
export {default as Orders} from './Orders';
export {default as ProductDetails} from './ProductDetails';
export {default as Products} from './Products';
export {default as Explore} from './Explore';
export {default as CheckOut} from './CheckOut';
