export {default as Hero} from './Hero'
export {default as TopCategory} from './TopCategory'
export {default as BestSales} from './BestSales'
export {default as CashbackSection} from './CashBack'
export {default as PopularProducts} from './PopularProducts'
export {default as CashBack2} from './CashBack2'